{% set name = "USalign" %}
{% set version = "20240303" %}
{% set sha256 = "10408172007c6c99abe69b0ba5b7848cbf980dd5701c0e27c5b7e57db9dc9cc4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://zhanggroup.org/US-align/bin/module/USalign.cpp  
  sha256: {{ sha256 }}

build:
  skip: True # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - which USalign

about:
  home: https://zhanggroup.org/US-align
  summary: 'US-align: universal structure alignment of monomeric and complex proteins and nucleic acids'
  description: |
    US-align (Universal Structural alignment) is a unified protocol
    to compare 3D structures of different macromolecules (proteins, RNAs and DNAs)
    in different forms (monomers, oligomers and heterocomplexes) for
    both pairwise and multiple structure alignments.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  # The doc_url and dev_url are optional.
  doc_url: https://zhanggroup.org/US-align/help/

extra:
  recipe-maintainers:
    - SSchott
